#!/usr/bin/env sh

cd "`dirname "$0"`/.."

docker run --runtime=nvidia \
	--rm -it \
	-p 127.0.0.1:6050:8888 \
	--ipc=host \
	-v "$(pwd)/nbs/":/fastai \
	keithmattix/fastai-coreos \
	jupyter notebook --no-browser --ip=0.0.0.0 --allow-root --NotebookApp.token= --notebook-dir='/fastai/'
